version: '3.8'

services:

  lexicom-redis:
    container_name: lexicom-redis-dev
    volumes:
      - lexicom-redis-data-dev:/bitnami/redis/data

  lexicom-api:
    container_name: lexicom-api-dev
    ports:
      - "18000:8000"
    env_file:
      - .env
    build:
      context: ./api
      dockerfile: dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    volumes:
      - ./api/app:/app

volumes:
  lexicom-redis-data-dev:
    driver: local
